@id = d2773336-f723-11e9-8f0b-362b9e155667
POST http://localhost:3000/api/patients/{{id}}/entries
Content-Type: application/json

{
    "date": "2025-08-23",
    "type": "Hospital",
    "specialist": "MD Checho",
    "diagnosisCodes": ["S62.5"],
    "description": "Gamed nonstop for 48 hours straight gooning to weird japanese games",
    "discharge": {
        "date": "2025-08-23",
        "criteria": "healthy enough"
    }
}