@id = M24.2 
# @id = M51.2
# @id = S03.5
# @id = J10.1
# @id = J06.9
# @id = Z57.1
# @id = N30.0
# @id = H54.7
# @id = J03.0
# @id = L60.1
# @id = Z74.3
# @id = L20

GET http://localhost:3000/api/diagnoses/{{id}}